version: '3.8'

services:
  flask:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sfdc
      POSTGRES_DB: flask_db
      POSTGRES_HOST: localhost
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sfdc
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
