name: Flask CI       #Workflow name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sfdc
          POSTGRES_DB: flask_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Checkout code           #retrieving the current version of the code from the repository
      uses: actions/checkout@v3     #predefined github actions

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Flask environment variables
      run: |
        export FLASK_APP=app.py
        export DATABASE_URL=postgresql://postgres:sfdc@localhost:5432/flask_db
        
    - name: Apply migrations
      run: flask db upgrade
  
    # - name: Run tests
    #   run: pytest
  
    # - name: Run linting
    #   run: |
    #     pip install flake8
    #     flake8 .   
    

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}   

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
            sachigaur/todo_cicd:latest
            sachigaur/todo_cicd:${{ github.sha }}

    - name: Post DockerHub image build success
      run: echo "Docker image built and pushed to Docker Hub."    
